### ISSUE TITLE
Magic Trackpad 2: why not smooth and stabile ?

### ISSUE THREAD

**Issue by YaPaY** [RicardoEPRodrigues/magicmouse-hid#11]
First of all i am sorry for my English. 

Mostly i am using hackintosh because trackpad is my 3rd hand. Today i tried to install pop os and see trackpad works or not on it. After that i installed your driver.
but, unfortunetely how can i say idk but trackpad does not work %100. The main problem is micro stuttering and not smooth like on MacOS. After a few minutes later its becoming more and more annoying. 

Just wanted to wrote my feedback. İ hope it would be better in future.

Many thanks for your grrat work and effort.

**Comment by RicardoEPRodrigues** [comment]
Hey, thank you for your report.

This repository is mainly focused on the Magic Mouse 2, although it picks up the support for the Trackpad. The thing is that [libinput](https://gitlab.freedesktop.org/libinput/libinput) actually supports the Magic Trackpad 2, so it is weird that it is not working as expected. What this also means is that, even without this driver, the main kernel should already support the Trackpad.

I advise you to search a bit more on the topic and try to find the specific issue.

Note: I do not own any Trackpad 2, so I cannot test it out.
