### ISSUE TITLE
Unstable Crashes Monitor OSD

### ISSUE THREAD

**Issue by Venganzarte** [RicardoEPRodrigues/magicmouse-hid#17]
Just thought i'd add this as i thought my Monitor had become faulty but in the end tracked it down to this driver.
Driver works with touchpad great but after around an hour functions from my monitor freeze.
1 i can no longer access OSD menu functions
2 Monitor will not turn off on shutdown just goes blank.
3 Monitor stays blank after restarting PC
4 Monitor and tablet work perfect on windows

Monitor is  43CVSUWD120HQ

**Comment by RicardoEPRodrigues** [comment]
Hey,

I appreciate your interest.

What OS are you using? Have you installed this driver manually? To use with an Apple's magic mouse.

To clarify, this driver was designed to support the Magic Mouse scrolling. Currently, it has been integrated with more recent Kernels (version 5.15 and up), so if you are using this particular driver installed through DKMS you can remove it and it should not impact your system (after a reboot).

**Comment by Venganzarte** [comment]
Hi, I am using KDE Neon, I removed driver now and monitor is functioning
again,
I tried both ways via deb and script but both have same effect. I also
tested on latest Ubuntu which again freezes monitor with driver.
I didn't realise a driver could stop monitor osd menu working ?

**Comment by RicardoEPRodrigues** [comment]
Neither did I!
