### ISSUE TITLE
Any way to adjust touch sensitivity?

### ISSUE THREAD

**Issue by tanc** [RicardoEPRodrigues/magicmouse-hid#2]
Thanks so much for your work on this, I've finally got an automatically connecting Magic Mouse on boot and after suspend.

I have a question though, do you know any way to adjust the touch sensitivity to make it more in line with how it behaves when connected to MacOS? At the moment it is too easy to trigger a scroll accidentally as the sensitivity to touch is so high. On MacOS I think it ignores the first few ticks of scrolling so it requires a bit more finger movement to activate. This helps reduce accidental touch events.

**Comment by tanc** [comment]
I've added a pull request with some code change to the `hid-magicmouse.c` code. Don't feel you have to merge it but I would be interested to hear your feedback. I'm going to use the driver for a couple of days and see if there are any problems or if it can be tweaked to have a natural feel like when using MacOS.

**Comment by RicardoEPRodrigues** [comment]
Fixed in aa53b84a690ddb2fa1958596aaca32aacda65daa
