### ISSUE TITLE
Send driver upstream

### ISSUE THREAD

**Issue by PhillipSz** [RicardoEPRodrigues/magicmouse-hid#8]
Hey,
thanks for the awesome driver! I have seen that in upstream linux the magicmouse driver https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/drivers/hid/hid-magicmouse.c does not have the changes you made. Have you considered sending them upstream? That way all people can benefit from them.

Thank you!

**Comment by RicardoEPRodrigues** [comment]
Hello, thank you!

I would love to, but I am very new to this whole driver scene, so I don't even know where to start.

For example, I do not know the correct way of connecting devices through Bluetooth to the driver other than the `udev` rules. Another one is that I don't have a MagicMouse1 where I can test my driver on and I could introduce regressions with no ways of fixing them.

If you or anyone has this knowledge and time, please do upload it to the kernel!

**Comment by johnchen902** [comment]
So I've sent the patches to LKML: https://lkml.org/lkml/2021/3/27/209
I didn't do the extra features (e.g. 3 finger), though.

**Comment by RicardoEPRodrigues** [comment]
@johnchen902 if all goes well, this repo won't be needed anymore correct?

In your patch, you fix the Bluetooth connection issue correct?

Let's hope it all goes well and we'll have mouse support native on Linux! :smile:

**Comment by johnchen902** [comment]
> this repo won't be needed anymore correct?

This patches have less feature than this repo, specifically (probably not exhaustive):
1. There's no middle_click_3finger, scroll_delay_pos_x, or scroll_delay_pos_y.
2. middle_button_{start,stop} is still -350/350. 

> In your patch, you fix the Bluetooth connection issue correct?

For me, yes. I should probably have asked more people to test the patches before sending them upstream. Do you want to try it yourselves?

**Comment by vchernin** [comment]
These patches appear to have now have been merged in the 5.13 kernel.

https://www.phoronix.com/scan.php?page=news_item&px=Linux-5.13-HID-Additions

https://lore.kernel.org/lkml/nycvar.YFH.7.76.2104292151220.18270@cbobk.fhfr.pm/

**Comment by PhillipSz** [comment]
Thanks everyone, for making this possible!
